### ISSUE TITLE
cannot match salt job with salt response (wrong parsing of salt job?)

### ISSUE THREAD

**Issue by Grayfoox** [kpetremann/salt-exporter#52]
hi,

not sure if its error on my side or not but exporter shows "job" as salt01, and not as job_ID. which makes hard to match new job and return for failed jobs.

![image](https://github.com/kpetremann/salt-exporter/assets/7593761/bb4f40ce-89c7-47d0-b8fc-9cabf88be106)

currently running on salt 3005.1
0.8.0 version of salt-exporter

![image](https://github.com/kpetremann/salt-exporter/assets/7593761/6e6ac9d3-51d7-49b1-a9bb-6d8ca1f4b577)

![image](https://github.com/kpetremann/salt-exporter/assets/7593761/1d363adf-f301-4942-a44d-1125a95fa665)

thanks

**Comment by kpetremann** [comment]
Hello @Grayfoox,

The label "job" is not exposed by the exporter. This is a default label Prometheus is adding when scraping the metrics.
It comes from your Prometheus configuration, which should look like:
```
scrape_configs:
  - job_name: salt1    #  <<<<<<<<<<<<< this is the value that Prometheus expose in "job" label
    static_configs:
      - targets: ["127.0.0.1:2112"]
```

The Job ID is not exposed because it would increase way too much the cardinality (number of metrics).

See the exposed labels (there are examples at the end of the page): https://kpetremann.github.io/salt-exporter/salt-exporter/metrics/

**Comment by Grayfoox** [comment]
thanks for info.

is there different way to match job and ret code?

I guess trough minion name and timedate.

Ok thanks for info

**Comment by kpetremann** [comment]
you can use the `salt_responses_total` or `salt_scheduled_job_return_total`, but it depends on how often you have jobs VS scraping interval.

Also, if you want to watch only one state or function, you can use `salt_function_status` and configure both filters to get what you want per minion:
```
  salt_function_status:
    enabled: true
    filters:
      functions:
        - "<the function you want>"
      states:
        - "<the state you want if needed>"
```
